name=input("Full Name: ")
address=input("Street Address: ")
city=input("City: ")
state=input("State: ")
zip=int(input("Zip Code: "))
telephone=input("Phone Number: ")
college=input("College Major: ")
Print ("                         ")
print("Name: "+name)
print("Address : " + address + " " + city + " " + state + " " + str(zip))
print("Phone Number : " + telephone)
print("College Major : " + college) 