item1=float(input("Price of Item 1 : "))
item2=float(input("Price of item 2 : "))
item3=float(input("Price of item 3 : "))
item4=float(input("Price of item 4 : "))
item5=float(input("Price of item 5 : "))
subtotal=(item1 + item2 + item3 + item4 + item5)
tax=(.06*subtotal)
total=(subtotal+tax)
print("Subtotal : " , subtotal)
print("Tax : ", tax)
print("Grand Total : ", total)